site_name: widget_saler
nav:
  - Home: README.md
  - Contributing: contributing.md
theme:
  name: 'material'
repo_url: https://github.com/Lee-W/widget_saler
remote_branch: gh-pages
remote_name: origin
