site_name: Widget Saler
nav:
  - Home: README.md
  - Contributing: contributing.md
theme:
  name: 'material'
repo_url: https://github.com/Lee-W/widget-saler
remote_branch: gh-pages
remote_name: origin
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
